---
# tasks file for netdata

- name: Install netdata
  apt:
    name: netdata
    state: present

- name: Netdata configuration
  template:
    src: netdata.conf.j2
    dest: "/etc/netdata/netdata.conf"
  notify: restart netdata

- name: Ensure netdata service is started and enabled at boot
  become: true
  service:
    name: netdata
    state: started
    enabled: yes

- name: Create nginx proxy config
  template:
    src: netdata_proxy.conf.j2
    dest: /etc/nginx/sites-available/netdata_proxy.conf

- name: Enable nginx proxy config
  file:
    src: /etc/nginx/sites-available/netdata_proxy.conf
    dest: /etc/nginx/sites-enabled/netdata_proxy.conf
    owner: www-data
    group: www-data
    state: link
  notify: reload nginx
